# Generated by Django 5.2.5 on 2025-08-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='media/', verbose_name='превью'),
        ),
    ]
